fix

diff --git a/.github/workflows/generate-docs.yml b/.github/workflows/generate-docs.yml
--- a/.github/workflows/generate-docs.yml
+++ b/.github/workflows/generate-docs.yml
@@ -1,4 +1,18 @@
-name: Generate Cobra Docs
+# Copyright 2023 The Nuclio Authors.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+name: Check for Nuctl Docs Updates
 
 on:
   pull_request:
@@ -6,7 +20,7 @@ on:
       - '**'
 
 jobs:
-  generate-docs:
+  check-docs:
     runs-on: ubuntu-latest
 
     steps:
@@ -21,13 +35,14 @@ jobs:
       - name: Generate Nuctl docs
         run: make generate-nuctl-docs
 
-      - name: Commit and push changes
+      - name: Check for changes in docs
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git checkout -b ${{ github.head_ref }}
-          git add docs/reference/nuctl/cli-docs
-          git commit -m "Auto-generate nuctl docs"
-          git push origin ${{ github.head_ref }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          if [[ -n $(git status --porcelain docs/reference/nuctl/cli-docs) ]]; then
+            echo "Documentation needs to be regenerated."
+            echo "::error::Documentation needs to be regenerated. Please run 'make generate-nuctl-docs' and commit the changes."
+            exit 1
+          else
+            echo "No changes in documentation."
+          fi
